name: Build/Release creation

on:
  push:
    branches: [ main ]
    tags: 'v*'
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v2
      id: cpu-cores

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-tags: true

    - name: Install marko
      run: python -m pip install marko

    - name: Configure CMake
      run: cmake -A x64 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j ${{ steps.cpu-cores.outputs.count }}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v3
      with:
        name: HDRTray
        path: ${{github.workspace}}/install

    - shell: bash
      run: |
        RELEASE_ARCHIVE=HDRTray-${GITHUB_REF/refs\/tags\//}.zip
        echo "RELEASE_ARCHIVE=$RELEASE_ARCHIVE" >> $GITHUB_OUTPUT
      id: release_archive_name
    - run: |
        7z a ${{ steps.release_archive_name.outputs.RELEASE_ARCHIVE }} ${{github.workspace}}/install/*
      name: Make release archive
      id: release_archive
      if: startsWith(github.ref, 'refs/tags/')
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: ${{ steps.release_archive_name.outputs.RELEASE_ARCHIVE }}
